### ISSUE TITLE
libKeyFinder Android Availability Issue

### ISSUE THREAD

**Issue by Diljeet** [mixxxdj/libkeyfinder#10]
Hi,
libKeyFinder is GPL based license
and we can't use it as an android shared library

Please distribute it under LGPL license so it can be used with android apps. Its a request.
I will compile it for android & will distribute compilation guide / sources on github.
Please change the licensing of libKeyFinder from GPL to LGPL, to support free development on mobile devices.

Thanks for your time
Sorry for contacting here

Edit:
I am trying to use it in my app named DiscDj, please tell me is it free or is there any fee to use it. I will use it as shared library with source distribution of this library only

**Comment by Be-ing** [comment]
There is no problem using GPL on Android.

Moreover we could not change the license even if we wanted to (which I would be opposed to even if we could). We did not write the software originally. All we have changed is the build system. The original author has already [refused a request to change it to LGPL](https://github.com/ibsh/libKeyFinder/issues/36).

If there are any changes needed to the build system to get it to build on Android, those contributions would be welcome. I am unfamiliar with Android development so I don't know what, if anything, would need to change.
