### ISSUE TITLE
Not an issue but Thank You!!

### ISSUE THREAD

**Issue by EvanPurkhiser** [mixxxdj/libkeyfinder#15]
Just wanted to say, I'm really happy this project found a new home!

Thank you so much for the work that's being put into this :)

Thank you for removing QT and replacing it with cmake, that was painful for me for a while!

I'll be updating my macOS homebrew recipie here https://github.com/EvanPurkhiser/homebrew-personal/blob/master/libkeyfinder.rb

Thank you again!

**Comment by Be-ing** [comment]
> I'll be updating my macOS homebrew recipie here https://github.com/EvanPurkhiser/homebrew-personal/blob/master/libkeyfinder.rb

It would be great if you could send this to upstream Homebrew.
