### ISSUE TITLE
Test failure on i586 with libkeyfinder 2.2.5

### ISSUE THREAD

**Issue by wally-mageia** [mixxxdj/libkeyfinder#18]
One tes fails on current Mageia Cauldron i586, the development version of Mageia Linux.

GCC version:
```
$ gcc --version
gcc (Mageia 11.2.1-0.20211225.1.mga9) 11.2.1 20211225
```

glibc:
```
$ rpm -qa glibc
glibc-2.34-20.mga9
```

Test failure:
```
49/65 Test #38: DownsamplerShortcutTest/EverythingWorksWithShortcutFactor ..............***Failed    0.07 sec
Filters: DownsamplerShortcutTest/EverythingWorksWithShortcutFactor

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
keyfinder-tests is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
DownsamplerShortcutTest/EverythingWorksWithShortcutFactor
-------------------------------------------------------------------------------
/home/wally/mgarepo/libkeyfinder/BUILD/libkeyfinder-2.2.5/tests/downsamplershortcuttest.cpp:24
...............................................................................

/home/wally/mgarepo/libkeyfinder/BUILD/libkeyfinder-2.2.5/tests/downsamplershortcuttest.cpp:70: FAILED:
  REQUIRE( (expected) >= (a.getSampleByFrame(i, j)) - 0.0000001 )
with expansion:
  262.77631f >= 262.7763136817

===============================================================================
test cases: 1 | 1 failed
assertions: 3 | 2 passed | 1 failed
```

**Comment by Be-ing** [comment]
Are you actually trying to use this on CPUs from the early 1990s?

**Comment by wally-mageia** [comment]
> Are you actually trying to use this on CPUs from the early 1990s?

No. Mageia still ships 32bit distro among others built with -march=i586 -mtune=generic.

**Comment by wally-mageia** [comment]
As a Mageia specific workaround all tests succeeds if `-ffloat-store` is appended to CXXFLAGS.

**Comment by Be-ing** [comment]
https://gcc.gnu.org/wiki/FloatingPointMath

> Note on x86 and m68080 floating-point math
> For legacy x86 processors without SSE2 support, and for m68080 processors, GCC is only able to fully comply with IEEE 754 semantics for the IEEE double extended (long double) type. Operations on IEEE double precision and IEEE single precision values are performed using double extended precision. In order to have these operations rounded correctly, GCC would have to save the FPU control and status words, enable rounding to 24 or 53 mantissa bits and then restore the FPU state. This would be far too expensive.
> The extra intermediate precision and range may cause flags not be set or traps not be raised. Also, for double precision, double rounding may affect the final results. Whether or not intermediate results are rounded to double precision or extended precision depends on optimizations being able to keep values in floating-point registers. The option -ffloat-store prevents GCC from storing floating-point results in registers. While this avoids the indeterministic behavior just described (at great cost), it does not prevent accuracy loss due to double rounding.
> On more modern x86 processors that support SSE2, specifying the compiler options -mfpmath=sse -msse2 ensures all float and double operations are performed in SSE registers and correctly rounded. These options do not affect the ABI and should therefore be used whenever possible for predictable numerical results. For x86 targets that may not support SSE2, and for m68080 processors, use long double where exact rounding is required and explicitly convert to float or double when necessary. Using long double prevents loss of 80-bit accuracy when values must be spilled to memory. See x87note for further details.
