### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [mixxxdj/libkeyfinder#21]
As per title: `packaging/libkeyfinder.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by Be-ing** [comment]
Please test the main branch now. If it works, I'll tag a new release.

**Comment by Be-ing** [comment]
Oh, CMake, footguns at every turn...

**Comment by alexshpilkin** [comment]
I can confirm this works for the purposes of Nixpkgs, but note that other consumers [frown upon](https://github.com/libjxl/libjxl/issues/1400#issuecomment-1122183126) having absolute paths in pkg-config files when they were *not* passed at configure time (the link points out msys2 and CPack specifically), thus the somewhat more compilcated approach taken by KDE in the link above. I’d say this is a joint CMake/pkg-config footgun.

**Comment by Be-ing** [comment]
Sorry for the delay following up on this... after thinking about it more, I am now thinking about reverting https://github.com/mixxxdj/libkeyfinder/commit/4e1a5022d4c91e3ecfe9be5c3ac7cc488093bd2e. The conventional practice for pkgconfig files is using path variables relative to a prefix. I know Nix works quite differently from other Unixy systems, but AFAIK it still preserves conventional directory structures within a package's prefix (`lib`, `include`, `bin` subdirectores within the prefix). Why does Nix specify absolute paths to CMake for the include and library directories? I don't understand why Nix doesn't simply specify an absolute path for `CMAKE_INSTALL_PREFIX` and leave `CMAKE_INSTALL_LIBDIR`/`CMAKE_INSTALL_INCLUDEDIR` unspecified or specified as the typical relative paths. This seems like an issue with the way Nix is using CMake breaking tons of upstream packages' assumptions (to be fair, it's also partially CMake's fault for allowing way too much complexity).

**Comment by alexshpilkin** [comment]
@Be-ing No worries, I’m still putting this whole thing together on my side as well :) It’s correct that the usual practice is prefix-relative paths (for the reasons mentioned in the link in my previous post) while Nix requires absolute ones. A way to handle *both* without much pain is in the KDE link in my original report (or, if you prefer, I can now put together a patch).

CMake’s implementation of `CMAKE_INSTALL{,_FULL}_*DIR` is more or less faithfully following the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/Directory-Variables.html) regarding installation directories; it is there that a piece of software is required to be able to spread itself over the filesystem at the installing user’s / downstream packager’s whim, with a derivation tree for directory variables about four levels deep. That is what you sign up for when you use those variables. The `prefix`/`exec_prefix` distinction (architecture-independent vs -dependent files) seems to have been lost in modern times, but Nix does use non-default values of `includedir` and `libdir`.

The reason Nix passes absolute paths is because they may legitimately need to be in different trees if development and/or documentation parts of a package are split. Roughly, in such a case you end up with
```shell
# default (user-oriented) output (this is where prefix and—in most cases—libdir point)
/nix/store/SHA256-foo-1.0/bin/blah
/nix/store/SHA256-foo-1.0/usr/lib/libfoo.so.1 # in some cases -dev makes more sense
/nix/store/SHA256-foo-1.0/usr/share/foo/somedata
# documentation output (this is where mandir and infodir point)
/nix/store/SHA256-foo-1.0-doc/usr/share/man/man1/foo.1
/nix/store/SHA256-foo-1.0-doc/usr/share/info/foo.info
# development output (this is where includedir points; .a files are manually moved after the fact)
/nix/store/SHA256-foo-1.0-dev/usr/include/foo.h
/nix/store/SHA256-foo-1.0-dev/usr/lib/libfoo.o
/nix/store/SHA256-foo-1.0-dev/usr/lib/pkgconfig/libfoo-1.0.pc
```
A GNU-compliant build system *should* be capable of handling this, but as we can see it’s not always implemented correctly. CMake makes this particularly error-prone because it has very rudimentary path manipulation pre-3.20 and provides relative directories by default (whereas autoconf-generated configure scripts, for example, take absolute libdir and includedir, so if the programmer wants relative ones they have to compute them explicitly).

**Comment by Be-ing** [comment]
Thanks for explaining. I understand why Nix specifies absolute paths now. I switched to using the `IS_ABSOLUTE` check and tagged a 2.2.7 release.
