### ISSUE TITLE
Windows DLL exports and std classes?

### ISSUE THREAD

**Issue by Be-ing** [mixxxdj/libkeyfinder#6]
Building dynamically for Windows, there are lots of warnings like:
```
 D:\a\libKeyFinder\libKeyFinder\src\exception.h(32,66): warning C4275: non dll-interface class 'std::runtime_error' used as base for dll-interface class 'KeyFinder::Exception' [D:\a\libKeyFinder\libKeyFinder\build\keyfinder.vcxproj]
```
I think these can be ignored as long as whatever executable links libkeyfinder is built with the same C++ standard library implementation? If so, should we disable these warnings? If that doesn't work and there is substantial work required to actually use libkeyfinder as a DLL on Windows, I think we should disable building dynamically on Windows.

**Comment by Be-ing** [comment]
Backing up, why is Windows CI building dynamically when we are using `-DVCPKG_TARGET_TRIPLET=x64-windows-static`?

**Comment by Holzhaus** [comment]
> Backing up, why is Windows CI building dynamically when we are using `-DVCPKG_TARGET_TRIPLET=x64-windows-static`?

That just says how the vcpkg-installed dependencies are used.

**Comment by Be-ing** [comment]
Apparently this works okay. :shrug:
